version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: splitly
      POSTGRES_PASSWORD: splitly
      POSTGRES_DB: splitly
    volumes:
      - splitly-pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  splitly-pgdata:
